# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-14 07:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('reminder_time', models.TimeField(blank=True, help_text='Time format is :HH:MM:SS', null=True)),
                ('assignements', models.ManyToManyField(blank=True, null=True, to='task.Assignment')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='assignments',
            field=models.ManyToManyField(related_name='assignments', to='task.Assignment'),
        ),
    ]
