# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-14 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='modified_time',
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_time',
            field=models.TimeField(blank=True, help_text='Time format is :HH:MM:SS', null=True),
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
        migrations.AddField(
            model_name='task',
            name='related_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_user', to='task.UserProfile'),
            preserve_default=False,
        ),
    ]
