# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-14 08:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0002_auto_20170614_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReminderSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignments',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='modified_time',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='assignements',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='reminder_time',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='user_id',
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_time',
            field=models.TimeField(blank=True, help_text='Time format is :HH:MM:SS', null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.AddField(
            model_name='taskremindersystem',
            name='related_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_doing_task', to='task.UserDetail'),
        ),
        migrations.AddField(
            model_name='taskremindersystem',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='task.Task'),
        ),
    ]
