# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-15 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20170615_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=10),
        ),
    ]
