# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-23 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20170623_0539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='person',
            new_name='person_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='person_id',
            new_name='person',
        ),
    ]
