# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-15 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20170615_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='person',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
