# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-23 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20170623_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='person_id',
        ),
    ]
