# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-22 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_remove_person_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.TimeField(blank=True, help_text=b'Time format is :HH:MM:SS', null=True)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_time',
            field=models.TimeField(blank=True, help_text=b'Time format is :HH:MM:SS', null=True),
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
