# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-24 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_notification_person_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='person_id',
            new_name='person',
        ),
    ]
