# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-22 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20170622_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
