# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-22 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20170622_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notify_user', to='task.Person'),
            preserve_default=False,
        ),
    ]
