# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-24 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20170624_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time_created',
            field=models.DateTimeField(blank=True, help_text=b'Time format is :HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='reminder_time',
            field=models.DateTimeField(blank=True, help_text=b'Time format is :HH:MM:SS', null=True),
        ),
    ]
